// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvN25Tqte7SffoA1Fo9lxhNVfqjPznB78',
    appId: '1:719178323161:web:52c5f7f454711cefebdac8',
    messagingSenderId: '719178323161',
    projectId: 'first-project-395117',
    authDomain: 'first-project-395117.firebaseapp.com',
    storageBucket: 'first-project-395117.appspot.com',
    measurementId: 'G-7RPN43SP4B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC72Kaet08WX1XJUTGsfezxhQQYxnlpRsU',
    appId: '1:719178323161:android:71ebd14e45d8938febdac8',
    messagingSenderId: '719178323161',
    projectId: 'first-project-395117',
    storageBucket: 'first-project-395117.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAcbK8Mbua4f7E4U5SrIP6_L-SkBdmbcU',
    appId: '1:719178323161:ios:f47eccc6c86a1ec5ebdac8',
    messagingSenderId: '719178323161',
    projectId: 'first-project-395117',
    storageBucket: 'first-project-395117.appspot.com',
    iosClientId: '719178323161-72hde49sj23sno8g48umj2cqlpdfcbdk.apps.googleusercontent.com',
    iosBundleId: 'us.parii.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAcbK8Mbua4f7E4U5SrIP6_L-SkBdmbcU',
    appId: '1:719178323161:ios:28ed1e5b5e877f80ebdac8',
    messagingSenderId: '719178323161',
    projectId: 'first-project-395117',
    storageBucket: 'first-project-395117.appspot.com',
    iosClientId: '719178323161-ct0l7jk7cakrs08ehhdjqjrbue3p10k2.apps.googleusercontent.com',
    iosBundleId: 'us.parii.firstApp.RunnerTests',
  );
}
